#!/bin/bash
#
# Copyright (C) Roman V. Posudnevskiy (ramzes_r@yahoo.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

ARGC=$#  # Number of args, not counting $0
i=1  # Used as argument index
cmd=${!i}
echo "vhd-tool call:">> /var/log/SMlog
echo "$0 $@" >> /var/log/SMlog

while [ $i -le $ARGC ];
do
    case ${!i} in
        --source-protocol)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            srcproto=${!i}
                        fi
                        ;;
        --source-format)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            srcfmt=${!i}
                        fi
                        ;;
        --destination-protocol)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            dstproto=${!i}
                        fi
                        ;;
        --destination-format)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            dstfmt=${!i}
                        fi
                        ;;
        --tar-filename-prefix)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            tarpfx=${!i}
                        fi
                        ;;
        --progress)
                        ARGS+=("${!i}")
                        progress="-p"
                        ;;
        --machine)
                        ARGS+=("${!i}")
                        machine="-m"
                        ;;
        --direct)
                        ARGS+=("${!i}")
                        direct=1
                        ;;
        --prezeroed)
                        ARGS+=("${!i}")
                        zero=1
                        ;;
        --path)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            path=${!i}
                        fi
                        ;;
        --source)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                        src=${!i}
                        fi
                        ;;
        --source-fd)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            srcfd=${!i}
                            let "srcfd = $srcfd - 2"
                        fi
                        ;;
        --destination)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            dst=${!i}
                        fi
                        ;;
        --destination-fd)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            dstfd=${!i}
                            let "dstfd = $dstfd - 2"
                        fi
                        ;;
        --destination-size)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            dstsz=${!i}
                        fi
                        ;;
        --relative-to)
                        i=$((i+1))
                        if [ -n "${!i}" ]; then
                            base=${!i}
                        fi
                        ;;
    esac
    i=$((i+1))
done
#rbdsrs=`xe sr-list type=rbd | grep uuid | awk '{print $5}'`
aiorbdsrs=`xe pbd-list device-config='image-type: aio' | grep sr-uuid | awk '{print $4} END {if (!NR) print "~~~"}'`
case "$cmd" in
    stream)
        case "$src" in
            *$aiorbdsrs*)
                if [ -n "$src" ] && [ "$srcproto"="none" ] && [ "$srcfmt"="hybrid" ] && [ -n "$dstfd" ]; then
                    #echo "`echo $src | awk -F: '{print $1}'`" > /tmp/vhd-tool.log
                    src_sr_uuid=`echo $src | awk -F: '{print $1}' | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $1}'`
                    src_vdi_uuid=`echo $src | awk -F: '{print $1}' | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $2}'`
                    #echo $src_sr_uuid >> /tmp/vhd-tool.log
                    #echo $src_vdi_uuid >> /tmp/vhd-tool.log
                    source=`rbd ls -l --pool RBD_XenStorage-$src_sr_uuid | awk '{print \$1}' | grep $src_vdi_uuid | egrep "SNAP-$src_vdi_uuid\$"`
                    if [ -z $source ]; then
                        source=`rbd ls -l --pool RBD_XenStorage-$src_sr_uuid | awk '{print \$1}' | grep $src_vdi_uuid | egrep "VHD-$src_vdi_uuid\$"`
                    fi
                    #echo $base >> /tmp/vhd-tool.log
                    base_sr_uuid=`echo $base | sed 's/\/run\/sr-mount\///g' | awk -F/ '{print $1}'`
                    base_vdi_uuid=`echo $base | sed 's/\/run\/sr-mount\///g' | awk -F/ '{print $2}'`
                    xe_pid=`pidof xe`
                    #echo "$xe_pid" >> /tmp/vhd-tool.log
                    #echo "$dstfd" >> /tmp/vhd-tool.log
                    dst_file_name=`readlink /proc/$xe_pid/fd/$dstfd`
                    #ls -la /proc/$xe_pid/fd/ >> /tmp/vhd-tool.log
                    if [ "$dstfmt" = "vhd" ]; then
                        if [ -z "$base_vdi_uuid" ]; then
                            #echo "rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | rbd2vhd -m -p --vhd $dst_file_name --rbd - --uuid $src_vdi_uuid 2>/dev/null" >> /tmp/vhd-tool.log
                            rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | rbd2vhd $machine $progress --vhd $dst_file_name --rbd - --uuid $src_vdi_uuid 2>/dev/null
                        else
                            from_snap="SNAP-$base_vdi_uuid"
                            #echo "rbd export-diff --from-snap $from_snap RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | rbd2vhd -m -p --vhd $dst_file_name --rbd - --uuid $src_vdi_uuid 2>/dev/null" >> /tmp/vhd-tool.log
                            rbd export-diff --from-snap $from_snap RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | rbd2vhd $machine $progress --vhd $dst_file_name --rbd - --uuid $src_vdi_uuid 2>/dev/null
                        fi
                    elif [ "$dstfmt" = "raw" ]; then
                        if [ -z "$base_vdi_uuid" ]; then
                            #echo "rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | rbd2vhd -m -p --vhd $dst_file_name --rbd - --uuid $src_vdi_uuid 2>/dev/null" >> /tmp/vhd-tool.log
                            rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | rbd2raw $machine $progress --vhd $dst_file_name --rbd - --uuid $src_vdi_uuid 2>/dev/null
                        else
                            echo "[ERROR]: Relative diff export is not supported with raw format"
                            exit 1
                        fi
                    fi
                else
                    IFS=""
                    /bin/vhd-tool-orig "$@"
                fi
                ;;
            *)
                IFS=""
                /bin/vhd-tool-orig "$@"
                ;;
        esac
        ;;
    *)
        IFS=""
        /bin/vhd-tool-orig "$@"
        ;;
esac
